### PR TITLE
Adding forked version of lib to be able to implement clear selection feature

### PR DESCRIPTION
**Pull request by mauricioac**
Forked library to be able to add these clear selection "x"s.

Added to ALL dropdowns.

screen shot 2018-04-09 at 16 31 47

### CODE REVIEW

**Comment by mauricioac** [comment]
[Allow user to select blank if they made a mistake on the measures form](https://trello.com/c/SGq8VGaN/138-allow-user-to-select-blank-if-they-made-a-mistake-on-the-measures-form)

**Comment by mauricioac** [comment]
[remove/unselect regulation](https://trello.com/c/X7SWSHkH/159-remove-unselect-regulation)

**Comment by mauricioac** [comment]
[unselect Measurement unit & Measurement unit qualifier](https://trello.com/c/W4Wzu17V/161-unselect-measurement-unit-measurement-unit-qualifier)

**Comment by matthewford** [comment]
@mauricioac need to specify the location of the fork

**Comment by mauricioac** [comment]
@matthewford I forked, but the actual lib is inside the "app/assets/javascripts/vendors".

Haven't pushed to my personal account.

**Comment by mauricioac** [comment]
Ideally we'd make a fork on BZ account and make a gem for it.

BUT, this is still selectize. Changing selectize to select2 is not actually easy, since some important features are missing on select2 as well.
So I thought we would leave the selectize -> select2 for beta, and just to allow users to clear selection, I have extended selectize.

If we'll keep using selectize, then yeah, making a proper fork and gem would be much better

**Comment by matthewford** [comment]
oh ok yea we can push that to a bz fork - I thought you found a fork ;)

**Pull request merged**
